appName: servicename
namespaceName: development

appImage: gcr.io/google-samples/microservices-demo/recommendationservice
appVersion: v0.10.1
appReplicasCount: 1
containerPort: 8080
containerEnvVars:
- name: PORT 
  value: 8080
servicePort: 8080
serviceType: ClusterIP
