appName: currency
namespaceName: development
appImage: gcr.io/google-samples/microservices-demo/currencyservice
appVersion: v0.10.1
appReplicasCount: 1
containerPort: 7000
containerEnvVars:
- name: PORT 
  value: "7000"
- name: DISABLE_PROFILER
  value: "1"
servicePort: 7000
serviceType: ClusterIP
healthProbePeriodSeconds: 10
