appName: email
namespaceName: development
appImage: gcr.io/google-samples/microservices-demo/emailservice
appVersion: v0.10.1
appReplicasCount: 1
containerPort: 8080
containerEnvVars:
- name: PORT 
  value: "8080"
- name: DISABLE_PROFILER
  value: "1"
servicePort: 5000
serviceType: ClusterIP
healthProbePeriodSeconds: 10
