appName: frontend
namespaceName: development
appReplicasCount: 1
appImage: gcr.io/google-samples/microservices-demo/frontend
appVersion: v0.10.1
containerPort: 8080
containerEnvVars:
- name: PORT
  value: "8080"
- name: PRODUCT_CATALOG_SERVICE_ADDR
  value: "productcatalog-service:3550"
- name: SHIPPING_SERVICE_ADDR
  value: "shipping-service:50051"
- name: PAYMENT_SERVICE_ADDR
  value: "payment-service:50051"
- name: EMAIL_SERVICE_ADDR
  value: "email-service:5000"
- name: CURRENCY_SERVICE_ADDR
  value: "currency-service:7000"
- name: CART_SERVICE_ADDR
  value: "cart-service:7070"
- name: RECOMMENDATION_SERVICE_ADDR
  value: "recommendation-service:8080"
- name: CHECKOUT_SERVICE_ADDR
  value: "checkout-service:5050"
- name: AD_SERVICE_ADDR
  value: "ad-service:9555"
- name: ENABLE_PROFILER
  value: "0"
- name: SHOPPING_ASSISTANT_SERVICE_ADDR
  value: "shoppingassistantservice:80"


