appName: recommendation
namespaceName: development
appImage: gcr.io/google-samples/microservices-demo/recommendationservice
appVersion: v0.10.1
appReplicasCount: 1
containerPort: 8080
containerEnvVars:
- name: PORT 
  value: "8080"
- name: DISABLE_PROFILER
  value: "1"
- name: PRODUCT_CATALOG_SERVICE_ADDR
  value: "productcatalog-service"
servicePort: 8080
serviceType: ClusterIP
healthProbePeriodSeconds: 10
