appName: shipping
namespaceName: development
appImage: gcr.io/google-samples/microservices-demo/shippingservice
appVersion: v0.10.1
appReplicasCount: 1
containerPort: 50051
containerEnvVars:
- name: PORT 
  value: "50051"
- name: DISABLE_PROFILER
  value: "1"
servicePort: 50051
serviceType: ClusterIP
healthProbePeriodSeconds: 10
