apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: frontend-scaledobject
  namespace: development
spec:
  scaleTargetRef:
    name: frontend-deployment  
  minReplicaCount: 1
  maxReplicaCount: 5
  triggers:
    - type: aws-cloudwatch
      metadata:
        namespace: "AWS/ApplicationELB"
        metricName: "RequestCountPerTarget"
        targetMetricValue: "50"  # Target value for requests per target
        threshold: "50"
        dimensionName: "k8s-developm-frontend-629648c58b"
        dimensionValue: "arn:aws:elasticloadbalancing:us-east-1:000685044917:targetgroup/k8s-developm-frontend-629648c58b/f738dfc6892d06e2"  # Replace with ALB Target Group ARN
        awsRegion: "us-east-1"            # Replace with your AWS region
        roleArn: "arn:aws:iam::000685044917:role/keda-role"  # The role you created
