---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: viewer-role-binding
roleRef:
  kind: ClusterRoleBinding
  name: viewer
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: Group 
    name: viewer-group
    apiGroup: rbac.authorization.k8s.io
