name: Terraform CI/CD Pipeline

on:
  pull_request:
    branches:
      - dev
      - release
    paths:
      - 'terraform/**'
  push:
    branches:
      - dev
      - release
    paths:
      - 'terraform/**'
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select environment to deploy to'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - prod

jobs:
  semgrep_scan:
    name: Semgrep Terraform Code Scan 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Install Semgrep
        run: python3 -m pip install semgrep
      - name: Run Semgrep Scan
        working-directory: terraform/
        run: semgrep --config "p/terraform"        
  
  sonar_scan:
    name: SonarCloud Terraform Code Scan 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Run SonarCloud Scan 
        uses: SonarSource/sonarcloud-github-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          projectBaseDir: 'terraform/'  
          args: >
            -Dsonar.organization=vmikhalskyi
            -Dsonar.projectKey=k8s
  
  plan_dev:
    if: (github.event_name == 'workflow_dispatch' && github.ref == 'refs/heads/dev')
    uses: ./.github/workflows/tf-plan.yml
    with: 
      ENV: ${{ github.event.inputs.environment }}
      TF_STATE_BUCKET: tfstate-mikhalskyi
      TF_STATE_PATH: dev-state/state.tfstate
    secrets:
      AWS_ROLE: ${{ secrets.AWS_ROLE_DEV }}

  apply_dev:
    if: (github.event_name == 'workflow_dispatch' && github.ref == 'refs/heads/dev')
    uses: ./.github/workflows/tf-apply.yml
    with: 
      ENV: ${{ github.event.inputs.environment }}
      TF_STATE_BUCKET: tfstate-mikhalskyi
      TF_STATE_PATH: dev-state/state.tfstate
    secrets:
      AWS_ROLE: ${{ secrets.AWS_ROLE_DEV }}

      











