name: Reusable Terraform Plan Workflow

on:
  workflow_call:
    inputs:
      ENV:
        required: true
        type: string
      TF_STATE_BUCKET:
        required: true
        type: string
      TF_STATE_PATH:
        required: true
        type: string
    secrets:
      AWS_ROLE:
        required: true

env:
  AWS_DEFAULT_REGION: us-east-1

jobs:
  plan:
    runs-on: ubuntu-latest
    permissions:
      id-token: write  
      contents: read
    steps:
      - name: Checkout Code 
        uses: actions/checkout@v4
        
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: AWS Configure OIDC credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE }}
          audience: personal-aws-02
          aws-region: ${{ env.AWS_DEFAULT_REGION }}

      - name: Terraform Init
        working-directory: "terraform/${{ inputs.ENV }}"
        run: terraform init -backend-config="bucket=${{ inputs.TF_STATE_BUCKET }}" -backend-config="key=${{ inputs.TF_STATE_PATH }}" -backend-config="region=us-east-1"

      - name: Terraform Validate
        working-directory: "terraform/${{ inputs.ENV }}"
        run: terraform validate

      - name: Terraform Plan
        working-directory: "terraform/${{ inputs.ENV }}"
        run: terraform plan -out=tfplan-${{ inputs.ENV }}.out

      - name: Upload Terraform Plan
        uses: actions/upload-artifact@v4
        with:
          name: terraform-plan-${{ inputs.ENV }}
          path: "terraform/${{ inputs.ENV }}/tfplan-${{ inputs.ENV }}.out"

      

